### ISSUE TITLE
404

### ISSUE THREAD

**Issue by manosriram** [AnubhavMadhav/Avengers-Of-GitHub#1]
404 Page on the result.

**Comment by AnubhavMadhav** [comment]
> 404 Page on the result.

Hey Mano!!
It's 404 at some times, because GitHub API allows only 60 requests per hour for unauthenticated users. Due to huge traffic on the web app, as I shared it few minutes ago, it may lead to 404, try after some time. It'll work for sure. And if you know any method to increase rate-limitting per hour, we can fix it.

**Comment by manosriram** [comment]
Oh ok I forgot that.

**Comment by AnubhavMadhav** [comment]
> Oh ok I forgot that.

It's Okay!!
